<a href="https://colab.research.google.com/github/princeiiitk/CampusX-ML/blob/main/OneHotEncoding/columnTransformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
!git clone 'https://github.com/princeiiitk/CampusX-ML'

fatal: destination path 'CampusX-ML' already exists and is not an empty directory.

In [42]:
import numpy as np
import pandas as pd

In [43]:
df=pd.read_csv('/content/CampusX-ML/ColumnsTransformer/covid_toy.csv')

In [44]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [46]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [63]:
df['city'].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [47]:
X=df.drop('has_covid',axis=1)
y=df['has_covid']

In [48]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=20)

In [49]:
X_train

    age  gender  fever   cough       city
21   73    Male   98.0    Mild  Bangalore
1    27    Male  100.0    Mild      Delhi
96   51  Female  101.0  Strong    Kolkata
69   73  Female  103.0    Mild      Delhi
19   42  Female    NaN  Strong  Bangalore
..  ...     ...    ...     ...        ...
28   16    Male  104.0    Mild    Kolkata
95   12  Female  104.0    Mild  Bangalore
15   70    Male  103.0  Strong    Kolkata
90   59  Female   99.0  Strong      Delhi
99   10  Female   98.0  Strong    Kolkata

[75 rows x 5 columns]

# Impute and concatination without columnTransformer

In [50]:
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])

In [51]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(75, 1)

In [52]:
ohe=OneHotEncoder(drop='first')
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city.shape

(75, 4)

In [53]:

# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(75, 1)

In [56]:
# X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# # also the test data
# X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

# X_train_transformed.shape

# Encoding and imputer with columnsTranformer

In [57]:
from sklearn.compose import ColumnTransformer

In [67]:
transformer=ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),
                                            ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
                                            ],
                              remainder='passthrough')

In [68]:
transformer.fit_transform(X_train).shape

(75, 7)

In [69]:

transformer.transform(X_test).shape

(25, 7)