<a href="https://colab.research.google.com/github/princeiiitk/CampusX-ML/blob/main/Binning%26Binarization/Binning%26Binarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
!git clone 'https://github.com/princeiiitk/CampusX-ML'

fatal: destination path 'CampusX-ML' already exists and is not an empty directory.

In [34]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [35]:
df=pd.read_csv('/content/CampusX-ML/Binning&Binarization/train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [36]:
df.isnull().sum()

Age         177
Fare          0
SibSp         0
Parch         0
Survived      0
dtype: int64

In [37]:
df.dropna(inplace=True)

In [38]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [39]:
df['family']=df['SibSp']+df['Parch']

In [40]:
df

      Age     Fare  SibSp  Parch  Survived  family
0    22.0   7.2500      1      0         0       1
1    38.0  71.2833      1      0         1       1
2    26.0   7.9250      0      0         1       0
3    35.0  53.1000      1      0         1       1
4    35.0   8.0500      0      0         0       0
..    ...      ...    ...    ...       ...     ...
885  39.0  29.1250      0      5         0       5
886  27.0  13.0000      0      0         0       0
887  19.0  30.0000      0      0         1       0
889  26.0  30.0000      0      0         1       0
890  32.0   7.7500      0      0         0       0

[714 rows x 6 columns]

In [41]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [42]:
df

      Age     Fare  Survived  family
0    22.0   7.2500         0       1
1    38.0  71.2833         1       1
2    26.0   7.9250         1       0
3    35.0  53.1000         1       1
4    35.0   8.0500         0       0
..    ...      ...       ...     ...
885  39.0  29.1250         0       5
886  27.0  13.0000         0       0
887  19.0  30.0000         1       0
889  26.0  30.0000         1       0
890  32.0   7.7500         0       0

[714 rows x 4 columns]

In [43]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=20)

In [45]:
X_train.head()

      Age      Fare  family
523  44.0   57.9792       1
433  17.0    7.1250       0
655  24.0   73.5000       2
698  49.0  110.8833       2
24    8.0   21.0750       4

In [46]:
# without binarization
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6256983240223464

In [48]:
df['family'].unique()

array([1, 0, 4, 2, 6, 5, 3, 7])

In [47]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6499608763693271)

In [54]:
from sklearn.preprocessing import Binarizer
trf=ColumnTransformer([(
    'bins',Binarizer(copy=False),['family']
)],remainder='passthrough')

In [55]:
X_train_transform=trf.fit_transform(X_train)
X_test_transform=trf.transform(X_test)

In [57]:
X_train_transform

array([[ 1.    , 44.    , 57.9792],
       [ 0.    , 17.    ,  7.125 ],
       [ 1.    , 24.    , 73.5   ],
       ...,
       [ 0.    , 45.    ,  8.05  ],
       [ 1.    , 24.    , 27.    ],
       [ 1.    , 25.    ,  7.775 ]])

In [58]:
clf=DecisionTreeClassifier()
clf.fit(X_train_transform,y_train)
y_pred=clf.predict(X_test_transform)
accuracy_score(y_test,y_pred)

0.6536312849162011

In [59]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6261541471048513)